package br.gov.school.projetos3.post.Enum;

public enum EnumNecessidades {
	HIGIENE,
	ALIMENTO,
	METERIAL_DE_CONSTRUCAO,
	MEDICAMENTO,
	VESTIMENTAS,
	MATERIAL_ESCOLAR,
	MARERIAIS_ASSISTIVOS,
	MATERIAL_DE_LIMPEZA
}